spring:
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/myecommerce_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    
    
server:
  servlet:
    context-path: /api
